"""
MIT License

Copyright (c) 2021 Riccardo Ferrero

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


from pyvista.utilities.helpers import vtk_points
import vtk
import pyvista as pv
import numpy as np
import math
import copy
from tqdm import tqdm
#from vtkmodules.vtkIOXML import vtkXMLPolyDataWriter
import vtkmodules.numpy_interface as np2vtk
from vtkmodules.vtkCommonDataModel import (
    vtkCellArray,
    vtkPolyData,
    vtkPolyLine,
    vtkGenericCell
)

parallelTransportNormalsArrayName = 'ParallelTransportNormals'
radiusArrayName = 'MaximumInscribedSphereRadius'

def createPolyline(Instructions=[],initial_diameter=1, startingPos=np.array([0,0,0]),fileOut='vessel',truncWithRoot=True):
    """
    This fnction take as input a list of instruction generated by vessel_generator.py and converts them in a vtk polyline using a turtle like approach
    """
    #SOME COMMON VMTK DATA ARRAY NAMES
    abscissasArrayName = 'Abscissas'

    if len(Instructions)==0:
        raise Exception("Instruction list is empty")
    else:
        print('Initializing drawing process')
        pos=[]
        diam=[]
        lines=[]
        truncLines=[]
        lines.append([0,1])
        points=[]
        t=my3Dturtle(coord=startingPos)
        pos.append([t.savePos(),0,0])
        points.append(t.storePoint())
        newline=[]
        newlineTrunc=[]
        newline.append(0)
        newlineTrunc.append(0)
        diam.append(initial_diameter)
        poly=pv.PolyData()  
        for instruction in tqdm(Instructions):
            if instruction[0]=='f':
                t.move(instruction[2])
                diam.append(instruction[1])
                points.append(t.storePoint())
                newline.append(points.__len__()-1)
                newlineTrunc.append(points.__len__()-1)
            elif instruction[0]=='+':
                t.turn(th=instruction[1])
            elif instruction[0]=='-':
                t.turn(th=-instruction[1])
            elif instruction[0]=='*':
                t.turn(ph=instruction[1])
            elif instruction[0]=='/':
                t.turn(ph=-instruction[1])
            elif instruction[0]=='[':
                pos.append([t.savePos(),points.__len__()-1,copy.deepcopy(newline)])
            elif instruction[0]==']':
                t.goBack(pos[-1][0][0],pos[-1][0][1],pos[-1][0][2],pos[-1][0][3])
                if newline[-1] is not lines[-1][-1]:
                    lines.append(copy.deepcopy(newline))
                    if truncWithRoot:
                        truncLines.append(copy.deepcopy(newline[-newlineTrunc.__len__()-1:]))
                    else:
                        truncLines.append(copy.deepcopy(newlineTrunc))
                newline=pos[-1][2]
                newlineTrunc.clear()
                newlineTrunc.append(pos[-1][1])
                pos.pop()
            else:
                #print(f"unrecognized instruction")
                pass #very wrong you should think about a error message
        lines.append(copy.deepcopy(newline))
        truncLines.append(copy.deepcopy(newlineTrunc))
        ppoints=np.stack(points) #stacks converts the array of arrays in a 2D array for the vtk_points function
        vtkPoints=vtk_points(ppoints)
        lines.sort(key=len,reverse=True)
        truncLines.sort(key=len,reverse=True)
        # Create a cell array to store the lines
        cells = vtkCellArray()
        cellsTrunc = vtkCellArray()
        endPoints=[]
        endPoints.append(-1)           
        print("Cleaning repeated lines")
        for i in  tqdm(range(1,len(lines))):
            if lines[i][-1] not in endPoints:
                endPoints.extend(lines[i])
                polyLine = vtkPolyLine()
                polyLine.GetPointIds().SetNumberOfIds(len(lines[i]))          
                for j in range(0, len(lines[i])):
                    polyLine.GetPointIds().SetId(j, lines[i][j])
                # add the lines to it
                cells.InsertNextCell(polyLine)
        cut_parameter=1
        if truncWithRoot:
            cut_parameter=2
        for i in  tqdm(range(0,len(truncLines))):
            if len(truncLines[i])>cut_parameter:
                polyLine = vtkPolyLine()
                polyLine.GetPointIds().SetNumberOfIds(len(truncLines[i]))          
                for j in range(0, len(truncLines[i])):
                    polyLine.GetPointIds().SetId(j, truncLines[i][j])
                # add the lines to it
                cellsTrunc.InsertNextCell(polyLine)
        
        endPointsCoord=[]

        # Create a polydata to store everything in
        polyData = vtkPolyData()
        polyDataTrunc= vtkPolyData()
        # Add the points to the dataset
        polyData.SetPoints(vtkPoints)
        polyDataTrunc.SetPoints(vtkPoints)
        # Add the lines to the dataset
        polyData.SetLines(cells)
        polyDataTrunc.SetLines(cellsTrunc)
        #Create data in vtk
        VTK_data = np2vtk.dataset_adapter.numpyTovtkDataArray(np.array(diam)*0.5,name=radiusArrayName)  ## Diameter *0.5 since in vtk  i store the maximum inscribed sphere radius
        polyData.GetPointData().SetScalars(VTK_data)
        polyDataTrunc.GetPointData().SetScalars(VTK_data)
        print(polyData.GetNumberOfCells())
        for i in range(0,polyData.GetNumberOfCells()):
            cell = vtkGenericCell()
            polyData.GetCell(i,cell)
            cellpointsnumber = cell.GetNumberOfPoints()
            if cellpointsnumber>0:
                endPoint=cell.GetPoints().GetPoint(cellpointsnumber-1)
                #print(endPoint)
                endPointsCoord.append(endPoint)
        """ potentially useful code snippets"""
        #velParam_numpy = 2*velArray 
        #velParam_vtk = numpy_to_vtk(velParam_numpy)
        #velParam_vtk.SetName('VelParam') #rememebr to give an unique name
        #data.GetPointData().AddArray(velParam_vtk) 
        np.savetxt(f"endPoints{fileOut}",endPointsCoord,fmt='%10.5f', delimiter=' ', newline='  ')
        WritePolyData(polyData,"vtk"+fileOut+".vtp",flag_ascii=1)
        WritePolyData(polyDataTrunc,"vtk"+fileOut+"Trunc.vtp",flag_ascii=1)
        pvData=pv.PolyData(polyData)
        ## Add data in pyvista
        pvData.point_data[radiusArrayName]=np.array(diam)*0.5
        tube = pvData.tube(scalars=radiusArrayName,absolute=True,capping=False)
        tube.plot(smooth_shading=True)
        tube.save(fileOut+".vtp")
        pvData.save(fileOut+"Center.vtp")
def visualizePair():
    artery=ReadPolyData('vtkArtery.vtp')
    vein=ReadPolyData('vtkVein.vtp')
    tubeA = pv.PolyData(artery).tube(radius=0.01,scalars=radiusArrayName,capping=False)
    tubeB = pv.PolyData(vein).tube(radius=0.01,scalars=radiusArrayName,capping=False)
    p = pv.Plotter()
    p.add_mesh(tubeA, color='red', opacity=0.5)
    p.add_mesh(tubeB, color="lightblue", opacity=0.5)
    p.show()

def CreateVoronoiDiagram(clFileName,numberOfInterpolationPoints,ofile="voronoiDiagram.vtp"):
    baseCl=ReadPolyData(clFileName)
    VoronoiDiagram=ConvertClToVoronoi(baseCl)
    numberOfLines=baseCl.GetNumberOfCells()
    numberOfPoints=baseCl.GetNumberOfPoints()
    print(f" Vessel segments: {numberOfLines}, Nodes: {numberOfPoints}")
    for i in tqdm(range(0,numberOfLines)):
        line=ExtractLine(i,baseCl)
        linePtsNumber=line.GetNumberOfPoints()

        newLinePoints=vtk.vtkPoints()
        newPointsNumber=numberOfInterpolationPoints*(linePtsNumber-1)

        newRadiusArray = vtk.vtkDoubleArray()
        newRadiusArray.SetNumberOfComponents(1)
        newRadiusArray.SetNumberOfTuples(newPointsNumber)
        newRadiusArray.SetName(radiusArrayName)
        newRadiusArray.FillComponent(0,0.0)
        count = 0
        for j in range(0,linePtsNumber-1):
            startPoint=line.GetPoint(j)
            startingRadius=line.GetPointData().GetArray(radiusArrayName).GetTuple1(j)
            endingRadius=line.GetPointData().GetArray(radiusArrayName).GetTuple1(j+1)
            
            direction=line.GetPointData().GetArray(parallelTransportNormalsArrayName).GetTuple3(j)
            avgRadiusStep=(endingRadius-startingRadius)/(numberOfInterpolationPoints+1)
            for k in range (1,numberOfInterpolationPoints):
                newVoronoiPoint = [0.0,0.0,0.0]
                newVoronoiPoint[0] = startPoint[0] + k*(1.0/numberOfInterpolationPoints)*direction[0]
                newVoronoiPoint[1] = startPoint[1] + k*(1.0/numberOfInterpolationPoints)*direction[1]
                newVoronoiPoint[2] = startPoint[2] + k*(1.0/numberOfInterpolationPoints)*direction[2]
                newRadius=startingRadius+float(k)*avgRadiusStep
                newLinePoints.InsertNextPoint(newVoronoiPoint)
                newRadiusArray.SetTuple1(count,newRadius)
                count=count+1
        VoronoiDiagram=InsertNewVoronoiPoints(VoronoiDiagram,newLinePoints,newRadiusArray)
    WritePolyData(VoronoiDiagram,ofile)

def InsertNewVoronoiPoints(oldDataset,newPoints,newArray):
    numberOfDatasetPoints = oldDataset.GetNumberOfPoints()
    numberOfNewPoints = newPoints.GetNumberOfPoints()
    numberOfNewVoronoiPoints = numberOfDatasetPoints + numberOfNewPoints
 
    newDataset = vtk.vtkPolyData()
    radiusArray = vtk.vtkDoubleArray()
    radiusArray.SetNumberOfComponents(1)
    radiusArray.SetNumberOfTuples(numberOfNewVoronoiPoints)
    radiusArray.SetName(radiusArrayName) 
    radiusArray.FillComponent(0,0.0)
    cellArray = vtk.vtkCellArray()  
    points = vtk.vtkPoints()
 
    for i in range(numberOfDatasetPoints):
       point = [0.0,0.0,0.0]
       oldDataset.GetPoint(i,point)
       points.InsertNextPoint(point)
       cellArray.InsertNextCell(1)
       cellArray.InsertCellPoint(i)
 
       value = oldDataset.GetPointData().GetArray(radiusArrayName).GetTuple1(i)
       radiusArray.SetTuple1(i,value)
 
    for i in range(numberOfNewPoints):
       point = [0.0,0.0,0.0]
       newPoints.GetPoint(i,point)
       points.InsertNextPoint(point)
       cellArray.InsertNextCell(1)
       cellArray.InsertCellPoint(numberOfDatasetPoints+i)
 
       value = newArray.GetTuple1(i)
       radiusArray.SetTuple1(numberOfDatasetPoints+i,value)
 
    newDataset.SetPoints(points)
    newDataset.SetVerts(cellArray)
    newDataset.GetPointData().AddArray(radiusArray)
    return newDataset

def ConvertClToVoronoi(cl):
    numberOfPoints=cl.GetNumberOfPoints()
    newDataset = vtk.vtkPolyData()
    radiusArray = vtk.vtkDoubleArray()
    radiusArray.SetNumberOfComponents(1)
    radiusArray.SetNumberOfTuples(numberOfPoints)
    radiusArray.SetName(radiusArrayName) 
    radiusArray.FillComponent(0,0.0)
    cellArray = vtk.vtkCellArray()  
    points = vtk.vtkPoints()

    for i in range(numberOfPoints):
       point = [0.0,0.0,0.0]
       cl.GetPoint(i,point)
       points.InsertNextPoint(point)
       cellArray.InsertNextCell(1)
       cellArray.InsertCellPoint(i)

       value = cl.GetPointData().GetArray(radiusArrayName).GetTuple1(i)
       radiusArray.SetTuple1(i,value)
    
    newDataset.SetPoints(points)
    newDataset.SetVerts(cellArray)
    newDataset.GetPointData().AddArray(radiusArray)
    return newDataset

def ExtractLine(cellid,centerlines):
   cell = vtk.vtkGenericCell()
   centerlines.GetCell(cellid,cell)

   numberOfPoints = cell.GetNumberOfPoints()

   line = vtk.vtkPolyData()
   cellArray = vtk.vtkCellArray()
   cellArray.InsertNextCell(numberOfPoints)

   linePoints = cell.GetPoints()

   ptnArray = vtk.vtkDoubleArray()
   ptnArray.SetNumberOfComponents(3)
   ptnArray.SetNumberOfTuples(numberOfPoints)
   ptnArray.SetName(parallelTransportNormalsArrayName)
   ptnArray.FillComponent(0,0.0)
   ptnArray.FillComponent(1,0.0)
   ptnArray.FillComponent(2,0.0)

   radArray = vtk.vtkDoubleArray()
   radArray.SetNumberOfComponents(1)
   radArray.SetNumberOfTuples(numberOfPoints)
   radArray.SetName(radiusArrayName)
   radArray.FillComponent(0,0.0)


   for i in range(numberOfPoints):
        cellArray.InsertCellPoint(i)   
        begPoint = linePoints.GetPoint(i)
        try:
            endPoint = linePoints.GetPoint(i+1)
        except:
            endPoint=begPoint
        vector = [0.0,0.0,0.0]
        vector[0] = endPoint[0] - begPoint[0]
        vector[1] = endPoint[1] - begPoint[1]
        vector[2] = endPoint[2] - begPoint[2]
        #vtk.vtkMath.Normalize(vector) 
        ptnArray.SetTuple3(i,vector[0],vector[1],vector[2])
        value =centerlines.GetPointData().GetArray(radiusArrayName).GetTuple1(cell.GetPointId(i))
        radArray.SetTuple1(i,value)
       
   line.SetPoints(linePoints)
   line.SetLines(cellArray) 
   line.GetPointData().AddArray(ptnArray)
   line.GetPointData().AddArray(radArray)
   return line

def ComputeSpline(startValue,endValue,numberOfPoints):
    averageValue = (startValue + endValue)/2.0
    averageId = int(numberOfPoints/2) 

    splineArray = vtk.vtkDoubleArray()
    splineArray.SetNumberOfComponents(1)
    splineArray.SetNumberOfTuples(numberOfPoints)
    splineArray.FillComponent(0,0.0)

    spline = vtk.vtkCardinalSpline()
    spline.AddPoint(float(0),startValue)
    spline.AddPoint(float(averageId),averageValue)
    spline.AddPoint(float(numberOfPoints),endValue)
    spline.Compute()   

    for i in range(numberOfPoints):
        splineArray.SetTuple1(i,spline.Evaluate(float(i)))
        print(spline.Evaluate(float(i)))    

    return splineArray 

def cube_minus_villi():
    pl = pv.Plotter()
    polyData=ReadPolyData('subcube_reconstructedmodel28.vtp')
    pvData=pv.PolyData(polyData)
    cube = pv.Cube((7.33,8.22,6.55),1,1,1).triangulate().subdivide(6)
    _ = pl.add_mesh(pvData, color='r')
    _ = pl.add_mesh(cube, color='b',style='wireframe', line_width=3)
    pl.show()
    result = cube.boolean_difference(pvData,progress_bar=True)

    result.plot(color='lightblue')
    result.save('cave_cube.vtp')
def plane_minus_villi():
    pl = pv.Plotter()
    polyData=ReadPolyData('subcube_reconstructedmodel28.vtp')
    pvData=pv.PolyData(polyData)
   
    plane = pv.Plane((7.43,8.2,6.56),(0.7,0.012,0.68),1,1).triangulate().subdivide(2)
    _ = pl.add_mesh(pvData, color='r')
    _ = pl.add_mesh(plane, color='b',style='wireframe', line_width=3)
    pl.show()
    result = plane.boolean_difference(pvData,progress_bar=True)
    result.plot(color='lightblue')
    result2 =plane.boolean_intersection(pvData,progress_bar=True)
    result2.plot(color='lightblue')
    result2.save('cave_plane.vtp')


class my3Dturtle:
    """
    my try yo implement a turtle like thing to move around and create the thing I need
    """
    def __init__(self,coord=np.array([0,0,0]),tan=np.array([1,0,0]),kappa=np.array([0,0,1]),speed=1.0):
        self.coord=coord
        self.tan=tan
        self.kappa=kappa
        self.speed=speed
    def move(self,speed=None):
        """
        propels the tortoise forward along the current direction at the given speed
        """
        if speed is not None:
            self.speed=speed
        self.coord=np.sum([self.coord,self.speed*self.tan], axis=0)
       
            
    def turn(self,th=0,ph=0):
        """
        turns the tortoise of theta and phi to face a new direction
        """
        q1=quatRot.angleAxes(th,self.kappa)
        self.tan=q1.rotate(self.tan)
        q2=quatRot.angleAxes(ph,self.tan)
        self.kappa=q2.rotate(self.kappa)


    def goBack(self,coord,tan,kappa,speed):
        """
        reset the tortoise position to a previously stored position and orientation.
        """
        self.coord=coord
        self.tan=tan
        self.kappa=kappa
        self.speed=speed
    
    def storePoint(self):
        return self.coord
    
    def savePos(self):
        return self.coord,self.tan,self.kappa,self.speed,0

class quatRot:
    """
    my try yo implement a superbasic rotation with quaternions
    can take as input a np arry of four elements and creates a unitari quaternion and its conjucate from it
    """
    def __init__(self,quat=np.array([-1.,0,0,0])):
        self.quat=self.normalize(quat)
        self.quati=np.array([quat[0],-quat[1],-quat[2],-quat[3]])
    @classmethod
    def angleAxes(cls,theta=np.pi/2,axis=np.array([1,0,0])):
        """
        takes an angle and an axes as input and passes to the class the rotation quaternion
        """
        quater=np.array([math.cos(theta/2),math.sin(theta/2)*axis[0],math.sin(theta/2)*axis[1],math.sin(theta/2)*axis[2]])
        return cls(quater)
    
    def rotate(self,vect=np.array([1,0,0])):
        self.vect=np.array([0,vect[0],vect[1],vect[2]])
        rotvect=quatMul(self.vect,self.quati)
        rotvect=quatMul(self.quat,rotvect)
        return rotvect[1:4]

    def normalize(self,quat, tolerance=0.00001):
        mag2 = sum(n * n for n in quat)
        if abs(mag2 - 1.0) > tolerance:
            mag = math.sqrt(mag2)
            quat = tuple(n / mag for n in quat)
        return np.array(quat)
    
def quatMul(q1,q2):
    w1, x1, y1, z1 = q1
    w2, x2, y2, z2 = q2
    w = w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2
    x = w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2
    y = w1 * y2 + y1 * w2 + z1 * x2 - x1 * z2
    z = w1 * z2 + z1 * w2 + x1 * y2 - y1 * x2
    return np.array([w, x, y, z])

def ReadPolyData(filename):
   reader = vtk.vtkXMLPolyDataReader()
   reader.SetFileName(filename)
   reader.Update()
   return reader.GetOutput()

def WritePolyData(input,filename,flag_ascii=0):
   writer = vtk.vtkXMLPolyDataWriter()
   writer.SetFileName(filename)
   writer.SetInputData(input)
   if flag_ascii:
    writer.SetDataModeToAscii()
   writer.Write()

def main():# used for debug purpose of function in this file
    #CreateVoronoiDiagram("vtkVesselTrunc.vtp",9)
    #CreateVoronoiDiagram("sub_cube28.vtp",64,'vor_diag_sub_cube_28.vtp')
    #♣cube_minus_villi()
    plane_minus_villi()

if __name__=='__main__':
    
    main()
      

