import vtk

def read_poly_data(file_path):
    """Read a .vtp PolyData vtk file such as centerlines and so on"""
    reader = vtk.vtkXMLPolyDataReader()
    reader.SetFileName(file_path)
    reader.Update()

    return reader.GetOutput()

def read_unstructured_grid(file_path):
    """Read a .vtk UnstructuredGrid vtk file. Thgis can be a tethrahedral mesh i.e. generated by GMSH"""
    reader = vtk.vtkUnstructuredGridReader()
    reader.SetFileName(file_path)
    reader.Update()
    return reader.GetOutput()

def read_structured_grid(file_path):
    """Read a .vtk StructuredGrid vtk file. (Cubes mesh with potentially variable dx dy dz) """
    reader = vtk.vtkStructuredGridReader()
    reader.SetFileName(file_path)
    reader.Update()
    return reader.GetOutput()

def read_structuredXML_mesh(file_path):
    """Read a .vtu StructuredXMLGrid vtk file. (Cubes mesh with potentially variable dx dy dz) """
    reader = vtk.vtkXMLStructuredGridReader()
    reader.SetFileName(file_path)
    reader.Update()
    return reader.GetOutput()

def write_unstructuredXML_mesh(mesh, file_path):
    """Write a .vtu UnstructuredXML mesh vtk file. This can be a tethrahedral mesh i.e.""" 
    writer = vtk.vtkXMLUnstructuredGridWriter()
    writer.SetFileName(file_path)
    writer.SetInputData(mesh)
    writer.Write()

def write_structuredXML_mesh(mesh,file_path):
    """Write a .vts StructuredGrid vtk file."""
    writer = vtk.vtkXMLStructuredGridWriter()
    writer.SetFileName(file_path)
    writer.SetInputData(mesh)
    writer.Write()

def save_cell_centers(cell_centers, file_path):
    """write a .vtp PolyData vtk file such as centerlines and so on REDUNDANT!!!!"""
    writer = vtk.vtkXMLPolyDataWriter()
    writer.SetFileName(file_path)
    writer.SetInputData(cell_centers)
    writer.Write()

def write_poly_data(input, filename, flag_ascii=0):
   """write a .vtp PolyData vtk file such as centerlines and so on"""
   writer = vtk.vtkXMLPolyDataWriter()
   writer.SetFileName(filename)
   writer.SetInputData(input)
   if flag_ascii:
    writer.SetDataModeToAscii()
   writer.Write()
